name: Publish Pypi
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.13
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        body_path: NEW-VERSION-CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}